### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
no clue why the mapfile changes....

**Comment by gary-kim** [comment]
Seems like the reason is because an absolute path to a file in the map file for some reason? Not sure why that is there now. 
Screenshot from 2020-05-11 23-03-30

**Comment by rullzer** [comment]
wait... we had that before...

**Comment by rullzer** [comment]
@ChristophWurst @juliushaertl I'm sure one of you remembers...

**Comment by ChristophWurst** [comment]
> @ChristophWurst @juliushaertl I'm sure one of you remembers...

https://github.com/nextcloud/firstrunwizard/commit/22cef53d658188af5d125808f14ede7568977ae5

**Comment by gary-kim** [comment]
Huh, that works. Something to keep in mind in case we run into this issue again.

**Pull request merged**
