### PR TITLE
Fix spacing for thumbnails and recommendations list

### PR DESCRIPTION
**Pull request by jancborchardt**
## Before
- Text of the bottom row was cut off
- Entries had small clickable area, felt cramped
- No padding to left of thumbnail
Recommendations before

## After
Recommendations after

Please review @ChristophWurst @nextcloud/designers

### CODE REVIEW

**Comment by gary-kim** [comment]
Huh, @jancborchardt mind if I rebase?

**Comment by skjnldsv** [comment]
> Huh, @jancborchardt mind if I rebase?

do it :)

**Comment by ChristophWurst** [comment]
- [ ] BLOCKED by https://github.com/nextcloud/recommendations/pull/151

**Comment by jancborchardt** [comment]
> Huh, @jancborchardt mind if I rebase?

Not at all, thanks! :)

@ChristophWurst I added a note about committing the build artifacts: https://github.com/nextcloud/recommendations/pull/157

**Comment by ChristophWurst** [comment]
@jancborchardt rebase

**Comment by jancborchardt** [comment]
> @jancborchardt rebase

Done! Hope it’s all good now? :D

**Pull request merged**
