### PR TITLE
perf(dashboard): implement widget item api v2

### PR DESCRIPTION
**Pull request by st3iny**
Ref https://github.com/nextcloud/server/pull/39937

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I've noticed a small feature regression. The old Vue widget allowed me to click on the preview of an image and open the file in the Viewer. The new API widget only offers a link to the file. Could that be a problem?

**Comment by ChristophWurst** [comment]
The feature was added with https://github.com/nextcloud/recommendations/commit/800310ae35b961fc4ab6d0133be0e04d63737359. So cc @juliushaertl

**Comment by juliushaertl** [comment]
Would be nice to have this back to avoid full page loads whenever possible, but probably less critical with 28 where the files app becomes a lot faster in loading with vue.

**Comment by ChristophWurst** [comment]
@jancborchardt @marcoambrosini @nimishavijay is it sufficient to have a quick files app and navigating to the recommended file or shall we revive the less performant widget with the direct viewer integration?

**Comment by jancborchardt** [comment]
Direct viewer integration is a much much nicer experience. (Otherwise the dashboard is always only a clunky jumping-off point instead of making it seamless.) Can we do that and get it more performant?

**Comment by ChristophWurst** [comment]
We can't. The new, performant widgets only work with standard lists. For the Viewer integration we need our own script.

**Comment by ChristophWurst** [comment]
Let's revert this PR @st3iny

In the future we might be able to advance the widget APIs again for an option to open Viewer for the thumbnail of an entry.

**Pull request merged**
