### PR TITLE
Update version on master

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
node is failing, it seems it's trying to compile something

**Review by marcoambrosini — APPROVED** [review]

**Comment by PVince81** [comment]
I've updated the outdated lock file, let's see if it fixes the compilation of node-sass...

**Comment by PVince81** [comment]
still failing on node-sass, let's see if we can upgrade it

**Comment by PVince81** [comment]
seems node-sass is not in package.json. @marcoambrosini I remember you had this issue in your local env, do you remember how we fixed it ?

**Comment by marcoambrosini** [comment]
I don't remember, but I'm pretty sure I did that together with @juliushaertl

**Comment by juliushaertl** [comment]
Build is failing on master as well with the same error and seems rather unrelated to the merged dependency updates.

My assumption is that this was due to the release of a newer node version and https://github.com/nextcloud/recommendations/pull/452 should fix this. I just triggered a build there so lets see.

**Comment by juliushaertl** [comment]
In general node-sass should not be used anymore, rather sass that comes as part of https://github.com/nextcloud/webpack-vue-config

**Comment by juliushaertl** [comment]
Strange it builds fine locally now with the same node/npm version 😕

**Comment by st3iny** [comment]
Superseded by https://github.com/nextcloud/recommendations/pull/465.

**Pull request closed without merging**
