### PR TITLE
Load recommendations with the initial page state

### PR DESCRIPTION
**Pull request by ChristophWurst**
As briefly discussed with @rullzer, this shouldn't be merged for Nextcloud 16 as we don't know if the recommendation queries are fast enough on bigger installation to load the files app page quickly.

Let's postpone this enhancement for 17. On small to medium sized installations this looks very quickly anyway.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@ChristophWurst What is the status here? We are close to the beta 1. Should this go into 17 or 18?

**Comment by rullzer** [comment]
Let me review and get it in.

**Comment by rullzer** [comment]
Lets do it for 18. As it seems there are some torubles with the recent searches. They should :tm: be fixed. But still good to double check before we do this.

**Comment by ChristophWurst** [comment]
> Let's postpone this enhancement for 17. On small to medium sized installations this looks very quickly anyway.

this is still true and the reason why I'm hesitating on the integration of this *enhancement* as it might make page loads unnecessarily slow and thus hurt the UX

**Comment by ChristophWurst** [comment]
I still don't think this is worth the optimization as it will potentially slow down the page load for larger installations.

**Pull request closed without merging**
