### PR TITLE
Revert "perf(dashboard): implement widget item api v2"

### PR DESCRIPTION
**Pull request by st3iny**
This reverts commit 52feace54cdd185630ec8d55cdd3b14385b270ab.

I tested this locally and the dashboard widgets works like it did before (builtin viewer etc.).

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by skjnldsv** [comment]
Status @st3iny ?

**Comment by susnux** [comment]
Can we somehow add a selector to the widget item API?
Meaning that it renders the widget with a class or ID assigned so we could hook into that.

So we could just use a very small script to add viewer support and still benefit from not needed to provide a full dashboard bundle

**Comment by skjnldsv** [comment]
@ChristophWurst @st3iny we're entering RC1, if this revert is important, it needs to get in asap! :+1: 

Otherwise, either close or change the milestone :pray:

**Comment by st3iny** [comment]
I rebased, resolved conflicts and tested again. I also fixed CI to finally make it green.

**Comment by st3iny** [comment]
@skjnldsv Your call regarding the merge. I'm not sure given that we had rc.1 already.

**Comment by Pytal** [comment]
`master` is now 30, moving to 30

**Pull request merged**
